### ISSUE TITLE
Configure AllowOnlineFetch

### ISSUE THREAD

**Issue by svrooij** [Zingabopp/JsonValidate-Action#3]
I was wondering why you have setup your code to do `allowOnlineFetch = false`.

https://github.com/Zingabopp/JsonValidate-Action/blob/713a469b2f1580f48bdbdb96f80c6897907103c5/src/main.ts#L35

Would it be possible to make this configurable? I have this json schema that loads other schemas and can thus only be verified if is allows loading those other files

**Comment by Zingabopp** [comment]
I added the option `allow-online-fetch`. Give `Zingabopp/JsonValidate-Action@master` a try and let me know if it works for you.
